# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            'Marcin Biegun'
sidebar_title:    'n23.pl'
tagline:          'splitting reality'
description:      'Marcin Biegun'
url:              http://n23.pl
baseurl:          /

author:
  name:           'Marcin Biegun'
  url:            http://n23.pl

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

social:
  twitter: kotutku
  github: marcinbiegun
  linkedin: mabiegun

integrations:
  google_analytics_id: 'UA-85551651-1'
